config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions:      'devise/sessions',
  passwords:     'devise/passwords',
  registrations: 'devise/registrations'
}

  root to: 'top#index'
  get 'about' => 'about#index'

  resources :topics do
    resource :topic_comments, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    get 'topics' => 'users#topics'
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'followers'
    get 'followers' => 'relationships#follower', as: 'follows'
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

  resources :maps, only: [:index, :create, :edit, :update, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates_uniqueness_of :post_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :name
    after_validation :geocode, if: :name_changed?
    belongs_to :user
    validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to  :user
    has_many    :favorites
    has_many    :favorited_users, through: :favorites, source: :user, dependent: :destroy
    has_many    :post_images, dependent: :destroy
    accepts_attachments_for :post_images, attachment: :image
    validates   :place_name, presence: true, length: {maximum: 20, minimum: 1}
    validates   :title, presence: true, length: {maximum: 20, minimum: 1}
    validates   :content, presence: true, length: {maximum: 200, minimum: 1}
    validates   :user_id, presence: true
    validates   :post_images, length: {maximum:5}
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :post
    attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates  :follower_id, presence: true
  validates  :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :user
    has_many :topic_comments, dependent: :destroy
    validates :title, presence: true, length: {maximum: 50, minimum: 1}
end

app/models/topic_comment.rb
class TopicComment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :name, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :topic_comments, dependent: :destroy
  has_many :maps, dependent: :destroy
  # has_many :maps, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

    def already_favorited?(post)
      self.favorites.exists?(post_id: post.id)
    end

    def following?(user)
      following_user.include?(user)
    end

    def follow(user_id)
      follower.create(followed_id: user_id)
    end
  
    def unfollow(user_id)
      follower.find_by(followed_id: user_id).destroy
    end

  attachment :image, destroy: false

  validates :name, presence: true, length: {maximum: 20, minimum: 1}
  validates :introduction, length: { maximum: 100 }
  validates :like_age, length: { maximum: 100 }
  validates :like_busho, length: { maximum: 100 }
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  before_action :correct_user, only: [:edit, :update]
  def new
    @topic = Topic.new
  end

  def index
    @topic = Topic.new
    @q = Topic.ransack(params[:q])
    @topics = @q.result(distinct: true).page(params[:page]).per(10).order(created_at: :desc)
    @topic_comments = @topic.topic_comments
  end

  def show
    @topic = Topic.find(params[:id])
    @topic_comment = TopicComment.new
    @topic_comments = @topic.topic_comments
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    if @topic.save
      redirect_to edit_topic_path(@topic.id), notice: "掲示板を作成しました！"
    else
      render "new"
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(topic_params)
      redirect_to edit_topic_path(@topic.id), notice: "掲示板のタイトルを更新しました！"
    else
      render "edit"
    end
  end

  def destroy
    topic = Topic.find(params[:id])
    topic.destroy
    redirect_to topics_path, notice: "掲示板を削除しました"
  end

  private
  def topic_params
    params.require(:topic).permit(:title)
  end
  def correct_user
    topic = Topic.find(params[:id])
    if current_user.id != topic.user.id
      redirect_to topics_path
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topics/edit.html.erb
<head>
  <% set_meta_tags title: "掲示板の編集", description: 'このページでは掲示板の内容を編集できます。' %>
</head>

<body>
  <br>
  <h1 class="text-align: text-center">
    <strong class="fas fa-edit">掲示板編集</strong></h1>
  <% if flash[:notice] %>
  <strong class="text-center alert alert-success"><%= flash[:notice] %></strong>
  <% end %>
  <div class="container">
    <br>
    <%= form_with model:@topic do |f| %>
    <form>
      <h2 class="strong"><%= f.label :タイトル, class:"fas fa-clipboard-list"%></h2>
      <%= f.text_field :title,class:'form-control'%>
      <%= f.submit "更新", class:'btn btn-primary btn-lg' %>
      <%= link_to "削除", topic_path(@topic.id), class:"btn btn-primary btn-lg", method: :delete, data: {confirm: "削除してもよろしいですか？"} %>
      <%= link_to "掲示板へ", topic_path(@topic.id), class:"btn btn-primary btn-lg" %>
    </form>
    <% end %>
  </div>
</body>

app/views/topics/index.html.erb
<head>
  <% set_meta_tags title: "掲示板", description: 'このページでは現在稼働中の掲示板を一覧で表示しております。ご自分にとって興味のあるトピックを扱っている掲示板に是非ご参加ください。' %>
</head>

<body>
  <div class="text-center">
    <br>
    <h1 class="fas fa-chalkboard-teacher">掲示板</h1>
    <div class="col-lg-4 col-md-7 mx-auto">
      <h2>
        <%= link_to "掲示板を作成する", new_topic_path, class:"far fa-plus-square"%>
      </h2>
      <br>
      <div class="form-group">
        <%= search_form_for @q do |f| %>
        <div class="input-group">
          <%= f.search_field :title_cont, class:'form-control', :placeholder => "タイトルを検索" %>
          <div class="input-group-append">
            <%= button_tag(class: "fas fa-search") do %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <% if flash[:notice] %>
    <p class="alert alert-danger"><%= flash[:notice] %></p>
    <% end %>
    <br>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>コメント数</th>
        </tr>
      </thead>
      <tbody>
        <% @topics.each do |topic| %>
        <tr class="table-primary">
          <td>
            <strong><%= link_to topic.title, topic_path(topic.id) %></strong>
          </td>
          <td><%= topic.topic_comments.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
      <div class="mx-auto">
        <%= paginate @topics %>
      </div>
    </div>
  </div>
</body>

app/views/topics/new.html.erb
<head>
  <% set_meta_tags title: "掲示板新規作成", description: 'このページで掲示板を新規作成できます。ご自分にとって興味のあるトピックを選んでご自由に作成してください' %>
</head>

<body>
  <div class="container">
    <br>
    <h2 class="text-align: text-center">
      <strong class="fas fa-chalkboard">掲示板作成</strong></h2>
    <div class="mx-auto">
      <%= form_with model:@topic, local: true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <form>
        <h2 class="strong"><%= f.label :タイトル, class:"fas fa-clipboard-list"%></h2>
        <%= f.text_field :title, class:'form-control' %>
        <%= f.submit "作成", class:"btn btn-primary btn-lg"%>
      </form>
      <% end %>
    </div>
  </div>
</body>

app/views/topics/show.html.erb
<body>
  <br>
  <h1 class="text-center"><strong><%= @topic.title %></strong></h1>
  <div class="container">
    <div class="row">
      <div class='mx-auto'>
        <div class="card" style="width: 700px">
          <% @topic_comments.each do |f| %>
          <div class="card-body">
            <div class="card-title">
              <strong><%= f.name %></strong>
              <small><%= f.created_at.to_s(:datetime_jp) %></small>
            </div>
            <div class="card-text">
              <%= safe_join(f.body.split("\n"), tag(:br)) %>
            </div>
            <% if current_user.id == f.user_id %>
            <%= link_to "削除", topic_topic_comments_path(f.id), class:"fas fa-trash-alt", method: :delete, data: { confirm: "削除してよろしいですか？"} %>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="mx-auto">
        <div class="card" style="width: 700px">
          <%= form_with model:@topic_comment, url: topic_topic_comments_path(@topic) do |f| %>
          <div class="card-body">
            <% if flash[:notice] %>
            <p class="alert alert-danger"><%= flash[:notice] %></p>
            <% end %>
            <h2 class="fas fa-comment">コメント</h2>
            <div class="card-text">
              <%= f.text_field :name, class:'form-control', :placeholder => "ユーザー名"  %>
            </div>
            <br>
            <div class="card-text">
              <%= f.text_area :body, class:'form-control', :placeholder => "コメント内容" %>
            </div>
            <%= f.submit 'コメントする', class:'btn btn-primary'%>
            <% end %>
            <br>
            <% if current_user.id == @topic.user_id %>
            <%= link_to "掲示板編集", edit_topic_path(@topic.id), class:"fas fa-wrench"%>
            <% else %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>