config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions:      'devise/sessions',
  passwords:     'devise/passwords',
  registrations: 'devise/registrations'
}

  root to: 'top#index'
  get 'about' => 'about#index'

  resources :topics do
    resource :topic_comments, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    get 'topics' => 'users#topics'
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'followers'
    get 'followers' => 'relationships#follower', as: 'follows'
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

  resources :maps, only: [:index, :create, :edit, :update, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :show, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :topic_comments, dependent: :destroy
  has_many :maps, dependent: :destroy
  # has_many :maps, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

    def already_favorited?(post)
      self.favorites.exists?(post_id: post.id)
    end

    def following?(user)
      following_user.include?(user)
    end

    def follow(user_id)
      follower.create(followed_id: user_id)
    end
  
    def unfollow(user_id)
      follower.find_by(followed_id: user_id).destroy
    end

  attachment :image, destroy: false

  validates :name, presence: true, length: {maximum: 20, minimum: 1}
  validates :introduction, length: { maximum: 100 }
  validates :like_age, length: { maximum: 100 }
  validates :like_busho, length: { maximum: 100 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :update]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(12).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10).order(created_at: :desc)
    @maps = Map.all.where(user_id: @user.id)
    @hash = Gmaps4rails.build_markers(@maps) do |map, marker|
      marker.lat map.latitude
      marker.lng map.longitude
      marker.infowindow map.name
    end
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to edit_user_path(@user.id), notice: "プロフィールを更新しました！"
    else
      render "edit"
    end
  end

  def following
    user = User.find(params[:user_id])
    @users = user.following_user
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.follower_user
  end

  def topics
    @topics = Topic.all.where(user_id: current_user.id).page(params[:page]).per(10).order(created_at: :desc)
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :image, :like_busho, :like_age)
    end

    def baria_user
      unless params[:id].to_i == current_user.id
        redirect_to new_user_session_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: user_relationships_path(@user), method: :post, remote: true) do |f| %>
<%= button_tag(class:"btn btn-success rounded-pill btn-sm") do %>
<%= content_tag :span, "フォロー", class: "fas fa-user-plus"%>
<% end %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render "unfollow" %>
        <% else %>
            <%= render "follow" %>
        <% end %>
    </div>
<% end %>

app/views/users/_follower&followed.html.erb
<table class='table text-center'>
  <thead>
    <tr>
      <th>プロフィール画像</th>
      <th>ユーザー</th>
      <th>フォロー</th>
      <th>フォロワー</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag(user, :image, :fill, 100, 100, class: "rounded-circle", fallback:
                    "no_image.jpg", size:'120x120') %></td>
      <td><strong><%= link_to user.name, user_path(user.id) %></strong></td>
      <td><strong><%= user.follower.count %></strong> </td>
      <td><strong class="text-center"><%= user.followed.count %></td></strong>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div class="mx-auto">
    <%= paginate @users %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="user-header">
  <div class="user-status row no-gutters">
    <div class="col-xs-12 col-md-2 text-center">
      <div class="user-img-area pt-3">
        <%= attachment_image_tag user, :image, :fill, 200, 200, class: "rounded-circle", fallback: "no_image.jpg", size:'180x180' %>
      </div>
    </div>
    <div class="col-xs-12 col-md-3 text-center">
      <div class="user-name">
        <%= user.name%>
      </div>
    </div>
    <div class="col-xs-12 col-md-2 text-center">
      <div class="follow-chat-btn">
        <%= render "follow_form" %>
        <div class="header-follow-text">
          <% if @user.id != current_user.id %>
          <%= render 'rooms/room', room: @room, roomId: @roomId, isRoom: @isRoom, entry: @entry, user: @user %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-5 text-center">
      <div class="follow-group">
        <div class="header-follow-text mr-5">
          <strong>フォロー</strong>
          <%= link_to user.follower.count, user_followers_path(user), style:"color:white" %>
        </div>
        <div class="header-follow-text">
          <strong>フォロワー</strong>
          <%= link_to user.followed.count, user_follows_path(user), style:"color:white" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row no-gutters">
    <div class="col-xs-12 col-md-5 mt-4 text-center">
      <div class="text-center mb-3 profile-title">プロフィール</div>
      <div class="user-info mt-3 ml-3">
        <div class="user-introduce mt-3 ml-3 mr-3">
          <div class="introduce">
            <div class="user-introduce">
              <% if user.introduction.blank? %>
              <p>まだ自己紹介はありません</p>
              <% else%>
              <%= safe_join(user.introduction.split("\n"), tag(:br)) %>
              <% end %>
            </div>
          </div>
          <div class="area user-age">
            <% if user.like_age.blank? %>
            <p>まだ登録していません</p>
            <% else %>
            <%= user.like_age %>
            <% end %>
          </div>
          <div class="area user-busho">
            <% if user.like_busho.blank? %>
            <p>まだ登録していません</p>
            <% else %>
            <%= user.like_busho %>
            <% end %>
          </div>
        </div>
        <% if @user.id == current_user.id %>
        <div class="setting">
          <%= link_to "プロフィールの編集" , edit_user_path, class:"fas fa-cog"%>
          <%= link_to "アカウント設定", edit_user_registration_path, class:"fas fa-cog"%>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-5 mt-4 mx-auto text-center">
      <div class="row text-center">
        <div class="user-map-title mx-auto text-center map-title">
          <%= user.name.to_s+"さんのスポットマップ" %></div>
        <div class="spot-map mt-3" id="map"
          style="width: 1000px; height: 400px; margin-left: auto; margin-right: auto;"></div>
        <script>
          handler = Gmaps.build('Google');
          handler.buildMap({
            provider: {},
            internal: {
              id: 'map'
            }
          }, function () {
            markers = handler.addMarkers( <%= raw @hash.to_json %> );
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            handler.getMap().setCenter(new google.maps.LatLng(38.258595, 137.6850225));
            handler.getMap().setZoom(5);
          });
        </script>
      </div>
    </div>
  </div>
</div>
<br>
<div class="col-md-8 mx-auto">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link active">
            <%= @user.name.to_s+"さんの投稿" %></a>
        </li>
        <% if @user == current_user %>
        <li class="nav-item">
          <%= link_to "作成した掲示板", user_topics_path(@user.id), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "チャット一覧", rooms_path, class:"nav-link" %>
        </li>
        <% else %>
        <% end %>
      </ul>
    </div>
  </div>
  <% @posts.each do |post| %>
  <div class="card">
    <div class="card-body">
      <small class="float-right"><%= post.created_at.to_s(:datetime_jp)  %></small>
      <h4 class="card-title"><strong><%= post.place_name %></strong></h4>
      <h5 class="card-subtitle"><strong><%= post.title %><strong></h5>
      <p class="card-text"><%= safe_join(post.content.split("\n"), tag(:br)) %></p>
      <div class="img-rounded pull-left profile-thum">
        <% post.post_images.each do |image| %>
        <%= attachment_image_tag image, :image, :fill, 140, 140, fallback: "no_image.jpg" %>
        <% end %>
      </div>
      <div id="favorites_buttons_<%= post.id %>">
        <%= render 'posts/favorite', post: post %>
      </div>
      <%= link_to "詳細", post_path(post), class:"fas fa-search-plus" %>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: user_relationships_path(@user), method: :delete, remote: true) do |f| %>
<%= button_tag(class:"btn btn-danger rounded-pill btn-sm") do %>
<%= content_tag :span, "フォロー中", class:"fas fa-user-minus" %>
<% end %>
<% end %>

app/views/users/edit.html.erb
<html>

<head>
  <% set_meta_tags title: "プロフィール編集", description: "に登録しているユーザーのプロフィールを編集することができます。"%>
</head>

<body>
  <strong class="text-center">
    <% if flash[:notice] %>
    <p class="alert alert-success"><%= flash[:notice] %></p>
    <% end %>
  </strong>
  <br>
  <div class="col-md7">
    <h1 class="text-align: text-center">
      <strong class="fas fa-user-edit">プロフィール編集</strong></h1>
    <br>
    <%= form_with model:@user, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="row no-gutters">
      <div class="card bg-light mx-auto">
        <div class="card-body">
          <table class="table md-0 table-responsive text-nowrap">
            <th>プロフィール画像</th>
            <td>
              <%= attachment_image_tag @user, :image, :fill, 200, 200, class: "rounded-circle", fallback: "no_image.jpg", size:'200x200'%><br>
              <%= f.attachment_field :image %>
            </td>
            <tr>
              <th>ユーザー名</th>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <th>自己紹介</th>
              <td><%= f.text_area :introduction, size: "50x5" %></td>
            </tr>
            <tr>
              <th>好きな時代</th>
              <td><%= f.text_field :like_age %></td>
            </tr>
            <tr>
              <th>好きな武将</th>
              <td><%= f.text_field :like_busho %></td>
            </tr>
          </table>
          <div class="text-center">
            <%= f.submit '変更を保存する', class:"btn btn-primary btn-lg" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</body>

</html>

app/views/users/index.html.erb
<head>
  <% set_meta_tags title: "ユーザーリスト", description: 'ヒストリアンに登録しているユーザーの一覧です。' %>
</head>

<body>
  <br>
  <h1 class="text-center fas fa-users">ユーザーリスト</h1>
  <br>
  <div class="col-lg-4 col-md-7 mx-auto">
    <div class="form-group">
      <%= search_form_for @q do |f| %>
      <div class="input-group">
        <%= f.search_field :name_cont, class:'form-control', :placeholder => "ユーザーを検索" %>
        <div class="input-group-append">
          <%= button_tag(class: "fas fa-search") do %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <% @users.each do |user| %>
      <div class="col-xs-12 col-md-6 col-lg-3 user-index">
        <div class="card user-card mt-1 ml-1 mr-1 mb-1">
          <%= attachment_image_tag user, :image, :fill, 200, 200, class: "rounded-circle mx-auto", fallback: "no_image.jpg", size:'240x240' %>
          <div class="card-body">
            <h2 class="card-title text-center">
              <strong><%= link_to user.name, user_path(user) %></strong>
            </h2>
            <div class="card-text text-center">
              <% if user.introduction.present? %>
              <%= truncate(user.introduction, length: 15) %>
              <% else %>
              まだ自己紹介はありません
              <% end %>
            </div>
            <div class="user-status-summary text-center mt-1">
              <div class="summary-title">フォロー
                <%= user.follower.count %></div>
              <div class="summary-title">フォロワー
                <%= user.followed.count %></div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="row">
      <div class="mx-auto">
        <%= paginate @users %>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<html>

<head>
  <% set_meta_tags title: "マイページ", description: 'に登録しているユーザーのプロフィールページを表示しております。' %>
</head>

<body>
  <strong class="text-center">
    <% if flash[:notice] %>
    <p class="alert alert-success"><%= flash[:notice] %></p>
    <% end %>
  </strong>
  <br>

  <h1 class="text-align: text-center">
    <strong class="fas fa-address-card">
      <%= @user.name.to_s+"さんのページ" %></a></strong></h1>
  <%= render 'profile', user: @user,now: ''%>
</body>

app/views/users/topics.html.erb
<head>
  <% set_meta_tags title: "ユーザーが作成した掲示板", description: 'ユーザーが作成した掲示板を一覧で表示しております。' %>
</head>

<body>
  <br>
  <h1 class="text-center">
    <strong class="fas fa-chalkboard-teacher">
      <%= current_user.name.to_s+"さんの掲示板"%></strong></h1>
  <% if @topics.count > 0 %>
  <table class='table text-center'>
    <thead>
      <tr>
        <th>タイトル</th>
        <th>コメント数</th>
      </tr>
    </thead>
    <tbody>
      <% @topics.each do |topic| %>
      <tr class="table-primary">
        <td><strong><%= link_to topic.title, topic_path(topic.id) %><strong></td>
        <td><%= topic.topic_comments.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @topics %>
    </div>
  </div>
  <% else %>
  <div class="mx-auto">
    <h2 class="display-4 text-info">まだ掲示板を作成していません</h2>
    <%= link_to "掲示板を作成する", new_topic_path, class:"btn btn-primary btn-lg"%>
    <% end %>
  </div>
</body>