config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions:      'devise/sessions',
  passwords:     'devise/passwords',
  registrations: 'devise/registrations'
}

  root to: 'top#index'
  get 'about' => 'about#index'

  resources :topics do
    resource :topic_comments, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    get 'topics' => 'users#topics'
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'followers'
    get 'followers' => 'relationships#follower', as: 'follows'
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

  resources :maps, only: [:index, :create, :edit, :update, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates_uniqueness_of :post_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :name
    after_validation :geocode, if: :name_changed?
    belongs_to :user
    validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to  :user
    has_many    :favorites
    has_many    :favorited_users, through: :favorites, source: :user, dependent: :destroy
    has_many    :post_images, dependent: :destroy
    accepts_attachments_for :post_images, attachment: :image
    validates   :place_name, presence: true, length: {maximum: 20, minimum: 1}
    validates   :title, presence: true, length: {maximum: 20, minimum: 1}
    validates   :content, presence: true, length: {maximum: 200, minimum: 1}
    validates   :user_id, presence: true
    validates   :post_images, length: {maximum:5}
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :post
    attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates  :follower_id, presence: true
  validates  :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :user
    has_many :topic_comments, dependent: :destroy
    validates :title, presence: true, length: {maximum: 50, minimum: 1}
end

app/models/topic_comment.rb
class TopicComment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :name, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :topic_comments, dependent: :destroy
  has_many :maps, dependent: :destroy
  # has_many :maps, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

    def already_favorited?(post)
      self.favorites.exists?(post_id: post.id)
    end

    def following?(user)
      following_user.include?(user)
    end

    def follow(user_id)
      follower.create(followed_id: user_id)
    end
  
    def unfollow(user_id)
      follower.find_by(followed_id: user_id).destroy
    end

  attachment :image, destroy: false

  validates :name, presence: true, length: {maximum: 20, minimum: 1}
  validates :introduction, length: { maximum: 100 }
  validates :like_age, length: { maximum: 100 }
  validates :like_busho, length: { maximum: 100 }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!

    def index
        @rooms = Room.all
        @user = @current_user
        @currentEntries = current_user.entries
            myRoomIds = []
        @currentEntries.each do |entry|
            myRoomIds << entry.room.id
        end
        @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?', @current_user.id).page(params[:page]).per(10)
    end

    def show
        @room = Room.find(params[:id])
        if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
            @message = Message.new
            @messages = @room.messages
            @entries = @room.entries
        else
            redirect_back(fallback_location: root_path)
        end
    end

    def create
        @room = Room.create
        @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
        @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
        redirect_to "/rooms/#{@room.id}"
    end

    def destroy
        room = Room.find(params[:id])
        room.destroy
        redirect_to rooms_path, notice: "チャットルームを削除しました!"
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/_room.html.erb
<% if isRoom == true %>
    <%= link_to "チャットへ", room_path(roomId), class:"btn btn-info rounded-pill  btn-sm fas fa-comments" %>
<% else %>
    <%= form_for room do |f| %>
    <%= fields_for entry do |e| %>
    <%= e.hidden_field :user_id, :value=> user.id %>
    <% end %>
    <%= button_tag(type: "submit", class: "btn btn-light rounded-pill btn-sm fas fa-comments") do %>
    チャットする
    <% end %>
    <% end %>
<% end %>

app/views/rooms/index.html.erb
<head>
  <% set_meta_tags title: "チャット一覧", description: 'ユーザーとのチャットの一覧を表示しております。' %>
</head>

<body>
  <br>
  <h1 class="text-center fas fa-comments">チャット一覧</h1>
  <br>
  <table class='table text-center'>
    <thead>
      <tr>
        <th>プロフィール画像</th>
        <th>ユーザー</th>
        <th>新着メッセージ</th>
      </tr>
    </thead>
    <% @anotherEntries.each do |e| %>
    <tbody>
      <tr class="table-secondary">
        <td>
          <%= attachment_image_tag e.user, :image, :fill, 100, 100, class: "rounded-circle", fallback: "no_image.jpg", size:'100x100' %>
        </td>
        <td>
          <strong class="text-center">
            <%= link_to e.user.name, user_path(e.user.id) %>
          </strong>
        </td>
        <td>
          <strong>
            <%= e.room.messages.order(created_at: :desc).take.try(:content) %><br>
          </strong>
          <%= link_to room_path(e.room.id) do %>
          <div class="btn btn-primary btn-sm">チャットルームへ</div>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @anotherEntries %>
    </div>
  </div>
</body>

app/views/rooms/show.html.erb
<head>
  <% set_meta_tags title: "チャット画面", description: 'ユーザーとのチャットを表示しております。' %>
</head>

<body>
  <div class="container">
    <%= render 'messages/message', messages: @messages %>
    <div class="chat_form">
      <%= form_for @message do |f| %>
      <div class="input-group mb-3">
        <%= f.text_field :content, class:'form-control', label:"Amount (to the nearest dollar)", :placeholder => "メッセージを入力して下さい" , :size => 70 %>
        <%= f.hidden_field :room_id, :value => @room.id %>
        <div class="input-group-append">
          <%= button_tag(class: "far fa-paper-plane") do %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <div>
      <strong>参加者:</strong>
      <% @entries.each do |e| %>
      <strong>
        <%= link_to e.user.name, user_path(e.user_id ) %>|
      </strong>
      <% end %>
    </div>
    <%= link_to "チャット一覧", rooms_path, class:"btn btn-primary" %>
  </div>
</body>