config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  sessions:      'devise/sessions',
  passwords:     'devise/passwords',
  registrations: 'devise/registrations'
}

  root to: 'top#index'
  get 'about' => 'about#index'

  resources :topics do
    resource :topic_comments, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    get 'topics' => 'users#topics'
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#followed', as: 'followers'
    get 'followers' => 'relationships#follower', as: 'follows'
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

  resources :maps, only: [:index, :create, :edit, :update, :destroy]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:index, :show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates_uniqueness_of :post_id, scope: :user_id
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :name
    after_validation :geocode, if: :name_changed?
    belongs_to :user
    validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to  :user
    has_many    :favorites
    has_many    :favorited_users, through: :favorites, source: :user, dependent: :destroy
    has_many    :post_images, dependent: :destroy
    accepts_attachments_for :post_images, attachment: :image
    validates   :place_name, presence: true, length: {maximum: 20, minimum: 1}
    validates   :title, presence: true, length: {maximum: 20, minimum: 1}
    validates   :content, presence: true, length: {maximum: 200, minimum: 1}
    validates   :user_id, presence: true
    validates   :post_images, length: {maximum:5}
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    belongs_to :post
    attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates  :follower_id, presence: true
  validates  :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :user
    has_many :topic_comments, dependent: :destroy
    validates :title, presence: true, length: {maximum: 50, minimum: 1}
end

app/models/topic_comment.rb
class TopicComment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :name, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :topic_comments, dependent: :destroy
  has_many :maps, dependent: :destroy
  # has_many :maps, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

    def already_favorited?(post)
      self.favorites.exists?(post_id: post.id)
    end

    def following?(user)
      following_user.include?(user)
    end

    def follow(user_id)
      follower.create(followed_id: user_id)
    end
  
    def unfollow(user_id)
      follower.find_by(followed_id: user_id).destroy
    end

  attachment :image, destroy: false

  validates :name, presence: true, length: {maximum: 20, minimum: 1}
  validates :introduction, length: { maximum: 100 }
  validates :like_age, length: { maximum: 100 }
  validates :like_busho, length: { maximum: 100 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def new
    @post = Post.new
    @post.post_images.build
  end

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @postnew = Post.new
    @favorite = Favorite.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post), notice: "投稿に成功しました!"
    else
      @posts = Post.all
      render 'index'
    end
  end

  def edit
    @post = Post.find(params[:id])
    @post.post_images.build
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: "投稿内容を更新しました!"
    else
      render "edit"
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: "投稿を削除しました!"
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :place_name, post_images_images: [])
  end

  def correct_user
    post = Post.find(params[:id])
    if current_user.id != post.user.id
      redirect_to posts_path
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def index
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_favorite.html.erb
<% if current_user.already_favorited?(post) %>
<%= link_to post_favorites_path(post, post_id: post.id), method: :delete, remote: true do %>
<span class="fas fa-thumbs-up">
    <%= post.favorites.count.to_s+"いいね" %></span>
<% end %>
<% else %>
<%= link_to post_favorites_path(post, post_id: post.id), method: :post, remote: true do %>
<span class="far fa-thumbs-up"><%= post.favorites.count.to_s+"いいね" %></span>
<% end %>
<% end %>

app/views/posts/_form.html.erb
<body>
  <div class="mx-auto">
    <%= form_with model: @post, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <form>
      <div class="form-group">
        <h2><%= f.label :訪れた場所, class:"fas fa-clipboard-list"%></h2>
        <%= f.text_field :place_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <h2><%= f.label :タイトル, class:"fas fa-clipboard-list" %></h2>
        <%= f.text_area :title, class: 'form-control'%>
      </div>
      <div class="form-group">
        <h2><%= f.label :本文, class:"fas fa-clipboard-list" %></h2>
        <%= f.text_area :content, class: 'form-control'%>
      </div>
      <div class="form-group">
        <h2><%= f.label :画像, class:"fas fa-images" %></h2>
        <%= f.attachment_field :post_images_images, multiple: true, class:"form-control-file" %>
        <small class="text-danger">画像は5枚まで投稿できます</small>
      </div>
      <%= f.submit "投稿する", class:'btn btn-primary btn-lg'%>
    </form>
    <% end %>
  </div>
</body>

app/views/posts/edit.html.erb
<html>

<head>
  <% set_meta_tags title: "投稿編集", description: "に登録しているユーザーが投稿した内容を編集することができます。"%>
</head>

<body>
  <br>
  <h1 class="text-align: text-center">
    <strong class="fas fa-edit">投稿編集</strong></h1>
  <div class="container">
    <%= render "posts/form", post: @post%>
    <br>
  </div>
</body>

</head>

app/views/posts/index.html.erb
<html>

<head>
  <% set_meta_tags title: "みんなの投稿", description: 'このページでは実際にユーザーが訪れた場所を一覧で表示しております。' %>
</head>

<body>
  <br>
  <h1 class="fas fa-clipboard text-align: text-center">
    みんなの投稿</h1>
  <br>
  <div class="col-lg-4 col-md-7 mx-auto">
    <div class="text-center">
      <h2><%= link_to "投稿する！", new_post_path, class: "fas fa-plus-circle" %></h2>
    </div>
    <br>
    <div class="form-group">
      <%= search_form_for @q do |f| %>
      <div class="input-group">
        <%= f.search_field :place_name_or_content_cont, class:'form-control', :placeholder => "投稿を検索" %>
        <div class="input-group-append">
          <%= button_tag(class: "fas fa-search") do %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <% if flash[:notice] %>
  <strong class="alert alert-danger text-center"><%= flash[:notice] %></strong>
  <% end %>
  <div class="container">
    <% @posts.each do |post| %>
    <div class="row mx-auto">
      <div class="col-lg-2 col-md-3 col-sm-4 col-xs-5 ">
        <div class="post_user mx-auto text-center">
          <%= attachment_image_tag post.user, :image, :fill, 200, 200, class: "rounded-circle", fallback: "no_image.jpg", size:'100x100' %>
          <h3><strong><%= link_to post.user.name, user_path(post.user)%></strong></h3>
        </div>
      </div>
      <div class="card col-lg-9 col-md-7 balloon2-left">
        <div class=" card-body">
          <small class="float-right"><%= post.created_at.to_s(:datetime_jp) %></small>
          <h4 class="card-title">
            <strong><%= post.place_name %></strong>
          </h4>
          <h5 class="card-subtitle"><strong><%= post.title %></strong></h5>
          <p class="card-text"><%= safe_join(post.content.split("\n"), tag(:br)) %></p>
          <div class="img-rounded pull-left profile-thum">
            <% post.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 140, 140, fallback: "no_image.jpg" %>
            <% end %>
          </div>
          <div id="favorites_buttons_<%= post.id %>">
            <%= render 'posts/favorite', post: post %>
          </div>
          <%= link_to "詳細", post_path(post), class:"fas fa-search-plus" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @posts %>
    </div>
  </div>
</body>

</html>

app/views/posts/new.html.erb
<html>

<head>
  <% set_meta_tags title: "投稿作成ページ", description: 'このページで自分が訪れた観光地の情報を入力して投稿することができます。' %>
</head>

<body>
  <br>
  <h1 class="mx-auto fas fa-edit">
    投稿</h1>
  <div class="container">
    <%= render "posts/form", post: @post %>
    <br>
  </div>
</body>

app/views/posts/show.html.erb
<body>
  <br>
  <h1 class="text-center"><strong class="fas fa-search-plus">投稿詳細</strong></h1>
  <% if flash[:notice] %>
  <strong class="alert alert-success text-center"><%= flash[:notice] %></strong>
  <% end %>

  <div class="container" style="max-width: 800px;">
    <div class="row mx-auto">
      <div class="col-lg-2 col-md-3 col-sm-4 col-xs-5 ">
        <div class="post_user mx-auto text-center">
          <h2>
            <%= attachment_image_tag @post.user, :image, :fill, 200, 200, class: "rounded-circle", fallback: "no_image.jpg", size:'100x100' %>
          </h2>
          <h3><strong><%= link_to @post.user.name, user_path(@post.user)%></strong></h3>
        </div>
      </div>
      <div class="card col-lg-9 col-md-7 balloon2-left">
        <div class=" card-body">
          <small class="float-right"><%= @post.created_at.to_s(:datetime_jp) %></small>
          <h4 class="card-title">
            <strong><%= @post.place_name %></strong>
          </h4>
          <h5 class="card-subtitle">
            <strong><%= @post.title %></strong>
          </h5>
          <p class="card-text"><%= safe_join(@post.content.split("\n"), tag(:br)) %></p>
          <div class="img-rounded pull-left profile-thum">
            <% @post.post_images.each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 140, 140, fallback: "no_image.jpg" %>
            <% end %>
          </div>
          <div id="favorites_buttons_<%= @post.id %>">
            <%= render 'posts/favorite', post: @post %>
          </div>
          <% if current_user.id == @post.user.id %>
          <%= link_to "編集", edit_post_path(@post.id), class:"fas fa-edit"%>
          <%= link_to "削除", post_path(@post.id), class:"fas fa-trash-alt", method: :delete, data: { confirm: "削除してよろしいですか？" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>